"""业务 / SDK / 系统错误码常量。

与 api-spec §错误码、sdk-adapter-design §错误标准化对齐。
业务代码应引用本模块，避免散落字符串字面量导致拼写不一致。
"""


class ErrorCode:
    # --- SYS ---
    SYS_DATABASE_UNAVAILABLE = "SYS_DATABASE_UNAVAILABLE"
    SYS_INVALID_CONFIG = "SYS_INVALID_CONFIG"
    SYS_VALIDATION_ERROR = "SYS_VALIDATION_ERROR"
    SYS_NOT_FOUND = "SYS_NOT_FOUND"
    SYS_HTTP_ERROR = "SYS_HTTP_ERROR"
    SYS_INTERNAL_ERROR = "SYS_INTERNAL_ERROR"

    # --- SDK ---
    SDK_NOT_CONFIGURED = "SDK_NOT_CONFIGURED"
    SDK_CONNECTION_FAILED = "SDK_CONNECTION_FAILED"
    SDK_AUTH_FAILED = "SDK_AUTH_FAILED"
    SDK_TIMEOUT = "SDK_TIMEOUT"
    SDK_RESPONSE_INVALID = "SDK_RESPONSE_INVALID"
    SDK_ORDER_REJECTED = "SDK_ORDER_REJECTED"
    SDK_CANCEL_REJECTED = "SDK_CANCEL_REJECTED"
    SDK_DISCONNECTED = "SDK_DISCONNECTED"

    # --- RISK ---
    RISK_SYSTEM_STOPPED = "RISK_SYSTEM_STOPPED"
    RISK_ALREADY_STOPPED = "RISK_ALREADY_STOPPED"
    RISK_CONFIRM_REQUIRED = "RISK_CONFIRM_REQUIRED"
    RISK_CONFIG_INVALID = "RISK_CONFIG_INVALID"
    RISK_RESUME_REASON_REQUIRED = "RISK_RESUME_REASON_REQUIRED"
    RISK_RESUME_BLOCKED = "RISK_RESUME_BLOCKED"
    RISK_UNKNOWN_ORDERS_PENDING = "RISK_UNKNOWN_ORDERS_PENDING"
    RISK_INVALID_STATE_TRANSITION = "RISK_INVALID_STATE_TRANSITION"
    RISK_CHECK_REQUIRED = "RISK_CHECK_REQUIRED"
    RISK_CHECK_NOT_PASSED = "RISK_CHECK_NOT_PASSED"
    RISK_CHECK_MISMATCH = "RISK_CHECK_MISMATCH"
    RISK_SYMBOL_BLOCKED = "RISK_SYMBOL_BLOCKED"
    RISK_DAILY_LOSS_LIMIT = "RISK_DAILY_LOSS_LIMIT"

    # --- ORDER ---
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_NOT_CANCELLABLE = "ORDER_NOT_CANCELLABLE"
    ORDER_CANCEL_FAILED = "ORDER_CANCEL_FAILED"
    ORDER_INVALID_TRANSITION = "ORDER_INVALID_TRANSITION"
    ORDER_NOT_UNKNOWN = "ORDER_NOT_UNKNOWN"
    ORDER_INVALID_RESOLVED_STATUS = "ORDER_INVALID_RESOLVED_STATUS"
    ORDER_CONFIRM_REQUIRED = "ORDER_CONFIRM_REQUIRED"
    ORDER_DUPLICATE_CLIENT_ID = "ORDER_DUPLICATE_CLIENT_ID"
    ORDER_STATUS_UNKNOWN = "ORDER_STATUS_UNKNOWN"

    # --- STRATEGY ---
    STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
    STRATEGY_CONFIRM_REQUIRED = "STRATEGY_CONFIRM_REQUIRED"
    STRATEGY_ALREADY_RUNNING = "STRATEGY_ALREADY_RUNNING"
    STRATEGY_NOT_RUNNING = "STRATEGY_NOT_RUNNING"
    STRATEGY_PARAM_INVALID = "STRATEGY_PARAM_INVALID"
    STRATEGY_RUNNING_PARAMS_LOCKED = "STRATEGY_RUNNING_PARAMS_LOCKED"
    STRATEGY_RUNTIME_ERROR = "STRATEGY_RUNTIME_ERROR"

    # --- AI ---
    AI_REPORT_NOT_FOUND = "AI_REPORT_NOT_FOUND"
    AI_REPORT_INVALID_RANGE = "AI_REPORT_INVALID_RANGE"
    AI_REPORT_NO_DATA = "AI_REPORT_NO_DATA"
    AI_REPORT_FAILED = "AI_REPORT_FAILED"
